
<?php
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
/*-----------------------Y&&C VOUS SHOUAITENT LA BIENVENUE-------------------------------- */
header('location: views/index.php');
?>